---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hamstersoftware/tienda.hamstersoftware.com/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .env.example $DEPLOYPATH 2>/dev/null || true
